### ISSUE TITLE
该项目是否支持ipv6？

### ISSUE THREAD

**Issue by charli2014** [lxrite/azure-http-proxy#1]
你好！很高兴看到这个项目。我想问一下项目本身支持ipv6协议不？
同时提一个建议，win版的客户端增加个最小化到托盘吧。

**Comment by lxrite** [comment]
你好，

这个项目是支持IPv6的。
比如可以通过下面四种格式为配置文件中的bind_address或proxy_server_address设置IPv6 loopback地址：
1. "0000:0000:0000:0000:0000:0000:0000:0001"
2. "[0000:0000:0000:0000:0000:0000:0000:0001]"
3. "::1"
4. "[::1]"

另外，Win版客户端之后会增加最小化到托盘的功能。

感谢你对本项目的关注和建议！

**Comment by sukenwoo** [comment]
Clang 编译缺少libatomic库

—

**Comment by charli2014** [comment]
非常感谢！

**Comment by lxrite** [comment]
@SukenWoo

你是在什么操作系统上编译的时候提示缺少libatomic库呢？
如果是在Mac OS上，可能Clang用的标准库是libc++而不是libstdc++，这种情况可能就不需要链接libatomic了（这个我也没测试过）。你可以把这行代码删掉试试
 [File: CMakeLists.txt line: 29](https://github.com/lxrite/azure-http-proxy/blob/a920f9c5956aab2c39eb38e3b58635f548bdc927/CMakeLists.txt#L29)

```
target_link_libraries(ahpc atomic)
```

然后删除CMake的缓存（清空上次执行cmake的目录），重新执行一次cmake。

**Comment by charli2014** [comment]
服务器端ipv6监听地址应该设置为`"::"`
