### ISSUE TITLE
可否提供mac下的可执行文件ahpc?

### ISSUE THREAD

**Issue by luckypoem** [lxrite/azure-http-proxy#10]
hi.

我在mac下make失败：

yudeMacBook-Air:azure-http-proxy brite$ cmake .
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   Regex
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/brite/azure-http-proxy
yudeMacBook-Air:azure-http-proxy brite$ make
[  6%] Linking CXX executable ahpc
ld: library not found for -latomic
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [ahpc] Error 1
make[1]: **\* [CMakeFiles/ahpc.dir/all] Error 2
make: **\* [all] Error 2
yudeMacBook-Air:azure-http-proxy brite$

how to fix it?thanks a lot.
或者你干脆提供mac下的可执行文件ahpc的下载地址？

**Comment by lxrite** [comment]
目前只会提供Windows的可执行文件，这里编译失败可以试试去掉这几行。

[File: CMakeLists.txt line: 28 - 30](https://github.com/lxrite/azure-http-proxy/blob/a920f9c5956aab2c39eb38e3b58635f548bdc927/CMakeLists.txt#L28-L30)

``` cmake
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  target_link_libraries(ahpc atomic)
endif()
```

**Comment by luckypoem** [comment]
@lxrite 
今天才看到你的答复。
我在自己的mac上，删除了CMakeLists.txt文件的第28 - 30行，再重新运行：
cmake .
make
成功生成了ahpc.
然后设置一番后，成功翻#墙。
