### ISSUE TITLE
有什么办法优化一下速度吗？

### ISSUE THREAD

**Issue by luckypoem** [lxrite/azure-http-proxy#11]
我在windows桌面系统现在可以成功的翻#墙了，不过速度好慢。有什么办法优化一下速度吗？

**Comment by luckypoem** [comment]
连youtube.com都打不开。

**Comment by luckypoem** [comment]
知道速度慢的原因了。应该是加密方式选得不合适，原来是aes-256-ofb,我把它改为aes-128-cfb,即可秒开youtube了。

**Comment by lxrite** [comment]
加密方法aes-128-cfb确实会比aes-256-ofb要快一些，但是应该也不会差很多。我自己一直用aes-256-ofb，在跑满带宽的情况下CPU使用率也不会超过0.1%。

不过既然修改加密方法可以解决打开慢的问题就可以了。

**Comment by luckypoem** [comment]
hi.

不过事实上，我表错情了。上面说的所谓“即可秒开youtube了”，其实当时用的代理我已经切换为lantern,所以误以为是azure-http-proxy加快了翻墙速度。在我切换回azure-http-proxy后，即使加密方式改为了aes-128-cfb，翻墙速度依然缓慢。所以还是想问问你，有什么办法优化一下速度吗？

**Comment by LetMeDecay** [comment]
速度慢还有可能是VPS的问题,线路不好
你可以装一个finalspeed,和ss一样配置就行

**Comment by github9751** [comment]
@luckypoem 打开/root/azure-http-proxy/ahps提示Failed to open "/root/.ahps/server.json"什么原因呢都是在同一目录呢，编译的ahps大小1.8M，环境为linux debian7 64，就是无法打开这个配置文件

**Comment by lxrite** [comment]
@qq975163418 把 server.json 文件复制到 /root/.ahps/ 这个目录下再试试。

**Comment by github9751** [comment]
经测试对比c++shadowsocks-libev，aph跑的带宽只能达到其一半，cpu还占用更高，sssever几乎不耗cpu。伤心，aphsever和client已经尝试过不加密，加大并发线程,233...还是很感谢呢@lxrite（刚才我竟然@错人了,笑哭，233）

**Comment by qq975163418** [comment]
我竟然@错人了,(哭，233

**Comment by huangfeidian** [comment]
我记得我以前测试过 youtube 4k的cpu占用很低的啊，以及打满流量占的cpu也是很低的，里面的执行内容也就http parse, encrypt/decrypt, network, 也许是里面的strand减慢的速度？
以及今天在reddit看到的一个回复
As someone that has ported libevent code to asio, I can confirm that asio is indeed slower than libevent, but only _by default_. You'd have to leverage a few tricks such as custom memory allocation for asio Handlers and use intrusive structures to store connection objects and a few others to attain libevent-level performance. These constructs  aren't too difficult to setup; one could even build a framework on top of asio that leverages this by default.

**Comment by lxrite** [comment]
目前我实际使用的时候是在部署了 ahps 的 VPS 上单边使用 Google 的 [BBR](https://github.com/google/bbr) 拥塞算法来改善 TCP 的传输速度，加速效果非常明显。
但是启用 BBR 需要 Linux Kernel 4.9 以上的内核，从另外一个 [Issue](https://github.com/lxrite/azure-http-proxy/issues/15) 了解到你和我一样使用的 OpenVZ 。OpenVZ 的内核版本比较旧，所以只能使用一些魔改的 BBR 方案，我目前使用的是 [tcp-nanqinlang/lkl-rinetd](https://github.com/tcp-nanqinlang/lkl-rinetd) 这个方案，你可以参考一下。

**Comment by lxrite** [comment]
@qq975163418 CPU占用高是不是在编译的时候没有开启优化导致的，是否开启优化对程序的运行效率差别是很大的。
实际使用的时候cmake 应指定 CMAKE_BUILD_TYPE 为 Release，这样在编译的时候才会使用 `-O3` 参数进行编译。
``` bash
cmake -DCMAKE_BUILD_TYPE=Release ..
```
后面我会对编译这里进行修改，如果没有指定 CMAKE_BUILD_TYPE 则默认为 Release 。
