### ISSUE TITLE
vs2015 boost 1.59 编译失败：boost optional 没有以nullptr为参数的构造函数

### ISSUE THREAD

**Issue by huangfeidian** [lxrite/azure-http-proxy#13]
这些错误基本都在一个文件里http_header_parser.h，好像是之前的boost版本支持nullptr自动转换为none把，现在的版本倒是不支持这个了。。。
重写这些函数的话，我用std::unique_ptr替换了所有的boost::optional，然后所有的return nulptr都换成了return std::make_unique<T>(nullptr)了，这样在vs2015上倒是能过，可是在linux上要求-std=c++14.......经测试gcc 4.9.3都无法支持make_unique，虽然我们可以用几行代码在c++11中模拟make_unique出来：
`template<typename T, typename... Args>
std::unique_ptr<T> make_unique(Args&&... args)
{
    return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
}`

**Comment by huangfeidian** [comment]
比较好的解决方案就是将return nullptr转换为return boost::optional<T>() ，这样就可以通过编译了。

**Comment by lxrite** [comment]
你使用的boost版本号是多少呢？

**Comment by huangfeidian** [comment]
1.59和1.60都试了，都挂在这个nullptr转optional上。
