### ISSUE TITLE
aes_ctr128 已经不在openssl 1.1.0里了，接口已经改变

### ISSUE THREAD

**Issue by huangfeidian** [lxrite/azure-http-proxy#14]
直接把这个加密删了吧

**Comment by lxrite** [comment]
好的，我周末处理一下。

**Comment by lxrite** [comment]
OpenSSL 1.1 的编译问题已解决。
从 OpenSSL 的 commit 记录来看，`AES_ctr128_encrypt ` 函数是在 [874a3757aff5ede013a825eea4b82a3e8ba96d34](https://github.com/openssl/openssl/commit/874a3757aff5ede013a825eea4b82a3e8ba96d34) 被移除的。
为了保持兼容，这里采用了相同的做法使用 `CRYPTO_ctr128_encrypt`函数来替代 `AES_ctr128_encrypt `函数。
