### ISSUE TITLE
ahps容易退出

### ISSUE THREAD

**Issue by luckypoem** [lxrite/azure-http-proxy#15]
有什么办法监视ahps进程，一旦其退出，就自动重启ahps？

**Comment by lxrite** [comment]
是什么原因导致的退出呢？我目前自己使用并没有遇到过 ahps 有会异常退出的情况。
ahps 本身并不提供自动重启的能力，如果需要可以写个 shell 脚本定时检测进程是否存在，如果不存在再自动拉起进程。这种脚本网上有许多现成的例子。

**Comment by luckypoem** [comment]
hi,
可能是openvz平台不好，导致ahps容易退出。
“如果需要可以写个 shell 脚本定时检测进程是否存在，如果不存在再自动拉起进程。”-我就是想达到这个目的，看了网上的许多现成的例子，但是还是不会写这样的脚本，你能写一个这样的脚本出来吗？
非常感谢你！

**Comment by lxrite** [comment]
不是 OpenVZ 的原因，我的 VPS 也是 OpenVZ 但是 ahps 可以稳定运行好几个月。
实现这样脚本只需要做2件事（参考网上的例子很容易自己实现的）。
- 根据名称判断进程是否存在
- 进程不存在时拉起进程

然后使用 crontab 等方法来定时执行这段脚本就可以实现你想要的目的。
