### ISSUE TITLE
There is no data received in the Client

### ISSUE THREAD

**Issue by ghost** [lxrite/azure-http-proxy#2]
Environment: Centos 6.5，GCC 4.9.1 OR 4.8.2, boost 5.7。
There is no Error appeared during compiling the ahps server&client.

Log:
cmake
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
.....
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   system
--   regex
.....
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/ahp/build

make:
Linking CXX executable ahps
[100%] Built target ahps

Server:
[root@test build]# ./ahps
Azure Http Proxy Server
bind address: 0.0.0.0:8090

The port condition when there is the linkage from the client:
tcp        0      0 0.0.0.0:8090                0.0.0.0:\*                   LISTEN      2188/./ahps
tcp        0      0 192.168.1.254:8090          192.168.1.2:59353           ESTABLISHED 2188/./ahps

服务端和客户端配置都启动成功。
但建立连接后，没有下行流量产生。
能否debug?

**Comment by ghost** [comment]
The capture about the connetction status in the Client couldn't be attached here,please get it as follow:
https://drive.google.com/file/d/0B4uKV-AeSn9ETU13OUN4dkNvNE0/view?usp=sharing

**Comment by lxrite** [comment]
你好，
你的用户代理（比如浏览器）是否设置的是HTTP代理呢？从你的截图来看每一次请求似乎只有6个字节，HTTP代理请求一般来说不会少于20个字节。
目前AHP暂时没有提供输出日志（DEBUG）的功能，之后会增加相关的功能。

**Comment by ghost** [comment]
@lxrite sorry, 是我疏忽了，之前的socks代理没有修改，现在测试正常，速度飞快~
多谢您的杰作。
