### ISSUE TITLE
今天出问题了

### ISSUE THREAD

**Issue by LetMeDecay** [lxrite/azure-http-proxy#3]
Azure Http Proxy Server
bind address: 0.0.0.0:8090
ahps: /usr/local/include/boost/optional/optional.hpp:641: boost::optional<T>::pointer_type boost::optional<T>::operator->() [with T = azure_proxy::http_request_header; boost::optional<T>::pointer_type = azure_proxy::http_request_header*]: Assertion `this->is_initialized()' failed.
Aborted
再次启动正常，过来报错一下
还有之前显示的是正常的，但是连接后没有速度

**Comment by lxrite** [comment]
你好，
你描述的这个错误和我在这次[Commit](https://github.com/lxrite/azure-http-proxy/commit/a920f9c5956aab2c39eb38e3b58635f548bdc927)中修复的问题有点像。报这个错误的ahps是否已经更新过这个Commit。
“连接后没有速度”是上下行都没速度吗？

**Comment by LetMeDecay** [comment]
这个是最开始的版本，好像是上下行都没速度

**Comment by lxrite** [comment]
最开始的版本的话，更新最新的代码应该就可以解决这个错误了。
一般来说客户端与服务端成功建立连接后是会立即产生上行流量的。
上下行都没速度应该是代理客户端无法与服务端建立连接，导致这种情况的原因可能是配置的服务端地址不正确、网络问题或者服务端ahps已经挂掉了。

**Comment by LetMeDecay** [comment]
我把源代码再更新一下，然后重新编译吧
