### ISSUE TITLE
操作wordpress 后台 新加 Paqe 之类的报错

### ISSUE THREAD

**Issue by kuyagic** [lxrite/azure-http-proxy#4]
说 bad request.错误.
应该任意 wp 后台 都会有这个问题. 可能是请求数据上处理的问题.

具体的晚些时候我发错误信息出来.

**Comment by lxrite** [comment]
你好，
  你使用的服务端ahps是最新的吗？我在 d4f39a8f7e4c54f9a3e96a32e4664d514468e1d1 修复了一个类似的问题。

感谢你的反馈:)

**Comment by kuyagic** [comment]
服务端是前几天 刚更新的. 
后台更新 文章的时候报错如下

502 Bad Gateway

Failed to check chunked response

找一个 wordpress 后台 更新一篇存在的文章 文章内容 稍微长一点 100% 重现这个bug.

**Comment by lxrite** [comment]
我的博客也是wordpress（webserver是nginx），我刚才按照你说的用最新ahps没有重现这个问题，你是用什么做的webbserver呢？

**Comment by kuyagic** [comment]
blog 是 wp 
webserver 是 nginx
前段 是 cloudflare
估计是 cf的问题. 
能否提供一个email 我把详细后台登陆发你 你可以测试 这个blog只是测试用的

**Comment by lxrite** [comment]
嗯，我没有用cloudflare。 我的邮箱是lxrite@gmail.com。

**Comment by kuyagic** [comment]
谢谢.邮件已发 请查收

**Comment by kuyagic** [comment]
用了最新的反馈. 测试正常了

多谢及时对应
