### ISSUE TITLE
这个程序的资源和宽带耗损如何？

### ISSUE THREAD

**Issue by cfcboy** [lxrite/azure-http-proxy#7]
比如网络环境一切正常的情况下，能达到满速吗？

比如SS的速度，这个更优于，还是？

**Comment by LetMeDecay** [comment]
我测试是比ss速度快的，占用感觉不高，可能是用的人不多吧

**Comment by huangfeidian** [comment]
然而 ss 作者被和谐。。。

**Comment by cfcboy** [comment]
@Dk2048 感谢回复，忘了过来看了。我试下实际实用感受。

**Comment by lxrite** [comment]
网络环境理想的情况下（不会丢包和极小的延迟），配置一般的个人PC速度也是可以跑满千兆网卡的。

速度上与SS（这里只比较Python实现的SS）比较：
1. 使用相同对称加密算法的情况下，C++实现的AHP会比Python实现的SS有更好的加解密性能；
2. 在Windows上处理大量的并发连接的情况下，AHP使用的IOCP会比SS使用的select有更高的效率；
3. AHP基于HTTP协议，SS基于SOCK5协议，在代理Web请求时SS在与源服务器断开连接的时候也必须和客户端断开连接，而AHP在与源服务器断开连接的时候如果条件允许会维持与客户端的连接，客户端之后的请求可以复用这个连接，省去了建立连接的开销。

不过，具体哪个更适合自己还是需要自己试过才知道的。
