### ISSUE TITLE
CentOS x64 cmake 出现错误。

### ISSUE THREAD

**Issue by cfcboy** [lxrite/azure-http-proxy#8]
CMake Error at /usr/lib64/boost/Boost.cmake:536 (message):
  The imported target "boost_date_time-static" references the file

```
 "/usr/lib64/lib64/libboost_date_time.a"
```

  but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  
   "/usr/lib64/boost/Boost.cmake"
  
  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib64/boost/BoostConfig.cmake:28 (include)
  /usr/share/cmake/Modules/FindBoost.cmake:177 (find_package)
  CMakeLists.txt:6 (find_package)

-- Configuring incomplete, errors occurred!
See also "/root/azure-http-proxy/build/CMakeFiles/CMakeOutput.log".

**Comment by cfcboy** [comment]
libboost_date_time.a
libboost_date_time-mt.a
libboost_date_time-d.a
这些哪来的？？？我编译安装boost也不行啊。要怎么搞

**Comment by daixiongming** [comment]
你好，这个算法用来加密商用软件怎么样？我想使用boost库的随机数，生成Keys,请问您觉得可行吗？期待您的回复：986876245@qq.com

**Comment by huangfeidian** [comment]
回楼上，随机数是不行的。key必须是ssl里生成的一个有效的对称加密key，你还是首先看一下作者写的readme吧。至于加密商业软件，这个不是当前代码干的事，你真的想用这个加密的话需要自己去剥离http proxy相关的那一部分。要是你真的完成了剥离，为啥不直接用asio with ssl呢。。。。。。

**Comment by lxrite** [comment]
这个编译错误比较奇怪，因为AHP没有依赖Boost.Date_Time。
不过最新的代码已经不依赖Boost库了，也就不会有这个编译错误了。
