### ISSUE TITLE
能支持openwrt吗？

### ISSUE THREAD

**Issue by ohyeah521** [lxrite/azure-http-proxy#9]
如题，如果要是可以支持openwrt的话，那么就完美了。

**Comment by lxrite** [comment]
因为我没有能刷OpenWrt的设备，所以暂时没办法支持OpenWrt。

**Comment by lxrite** [comment]
已经支持 OpenWrt了。 参考 [openwrt-ahp](https://github.com/lxrite/openwrt-ahp)
